# -*- coding: utf-8 -*-
##############################################
# Export CloudWatch metric data to csv file
# Configuration file
##############################################

METRICS = {
	'CPUUtilization': ['AWS/EC2', 'AWS/RDS'],
	'CPUCreditUsage': ['AWS/EC2', 'AWS/RDS'],
	'CPUCreditBalance': ['AWS/EC2', 'AWS/RDS'],
	'DiskReadOps': ['AWS/EC2'],
	'DiskWriteOps': ['AWS/EC2'],
	'DiskReadBytes': ['AWS/EC2'],
	'DiskWriteBytes': ['AWS/EC2'],
	'NetworkIn': ['AWS/EC2'],
	'NetworkOut': ['AWS/EC2'],
	'NetworkPacketsIn': ['AWS/EC2'],
	'NetworkPacketsOut': ['AWS/EC2'],
	'MetadataNoToken': ['AWS/EC2'],
	'CPUSurplusCreditBalance': ['AWS/EC2'],
	'CPUSurplusCreditsCharged': ['AWS/EC2'],
	'EBSReadOps': ['AWS/EC2'],
	'EBSWriteOps': ['AWS/EC2'],
	'EBSReadBytes': ['AWS/EC2'],
	'EBSWriteBytes': ['AWS/EC2'],
	'EBSIOBalance%': ['AWS/EC2'],
	'EBSByteBalance%': ['AWS/EC2'],
	'StatusCheckFailed': ['AWS/EC2'], 
	'StatusCheckFailed_Instance': ['AWS/EC2'],
	'StatusCheckFailed_System': ['AWS/EC2'],
	'BinLogDiskUsage': ['AWS/RDS'], 
	'BurstBalance': ['AWS/RDS'], 
	'DatabaseConnections': ['AWS/RDS'], 
	'DiskQueueDepth': ['AWS/RDS'], 
	'FailedSQLServerAgentJobsCount': ['AWS/RDS'], 
	'FreeableMemory': ['AWS/RDS'], 
	'FreeStorageSpace': ['AWS/RDS'], 
	'MaximumUsedTransactionIDs': ['AWS/RDS'], 
	'NetworkReceiveThroughput': ['AWS/RDS'], 
	'NetworkTransmitThroughput': ['AWS/RDS'], 
	'OldestReplicationSlotLag': ['AWS/RDS'], 
	'ReadIOPS': ['AWS/RDS'], 
	'ReadLatency': ['AWS/RDS'], 
	'ReadThroughput': ['AWS/RDS'], 
	'ReplicaLag': ['AWS/RDS'], 
	'ReplicationSlotDiskUsage': ['AWS/RDS'], 
	'SwapUsage': ['AWS/RDS'], 
	'TransactionLogsDiskUsage': ['AWS/RDS'], 
	'TransactionLogsGeneration': ['AWS/RDS'], 
	'WriteIOPS': ['AWS/RDS'], 
	'WriteLatency': ['AWS/RDS'], 
	'WriteThroughput': ['AWS/RDS'], 
	'ActiveConnectionCount': ['AWS/ApplicationELB'], 
	'ClientTLSNegotiationErrorCount': ['AWS/ApplicationELB'], 
	'ConsumedLCUs': ['AWS/ApplicationELB'], 
	'DesyncMitigationMode_NonCompliant_Request_Count': ['AWS/ApplicationELB'], 
	'HTTP_Fixed_Response_Count': ['AWS/ApplicationELB'], 
	'HTTP_Redirect_Count': ['AWS/ApplicationELB'], 
	'HTTP_Redirect_Url_Limit_Exceeded_Count': ['AWS/ApplicationELB'], 
	'HTTPCode_ELB_3XX_Count': ['AWS/ApplicationELB'], 
	'HTTPCode_ELB_4XX_Count': ['AWS/ApplicationELB'], 
	'HTTPCode_ELB_5XX_Count': ['AWS/ApplicationELB'], 
	'HTTPCode_ELB_500_Count': ['AWS/ApplicationELB'], 
	'HTTPCode_ELB_502_Count': ['AWS/ApplicationELB'], 
	'HTTPCode_ELB_503_Count': ['AWS/ApplicationELB'], 
	'HTTPCode_ELB_504_Count': ['AWS/ApplicationELB'], 
	'IPv6ProcessedBytes': ['AWS/ApplicationELB'], 
	'IPv6RequestCount': ['AWS/ApplicationELB'], 
	'NewConnectionCount': ['AWS/ApplicationELB'], 
	'NonStickyRequestCount': ['AWS/ApplicationELB'], 
	'ProcessedBytes': ['AWS/ApplicationELB'], 
	'RejectedConnectionCount': ['AWS/ApplicationELB'], 
	'RequestCount': ['AWS/ApplicationELB'], 
	'RuleEvaluations': ['AWS/ApplicationELB'], 
	'HTTPCode_Target_2XX_Count': ['AWS/ApplicationELB'], 
	'HTTPCode_Target_3XX_Count': ['AWS/ApplicationELB'], 
	'HTTPCode_Target_4XX_Count': ['AWS/ApplicationELB'], 
	'HTTPCode_Target_5XX_Count': ['AWS/ApplicationELB'], 
	'TargetConnectionErrorCount': ['AWS/ApplicationELB'], 
	'TargetResponseTime': ['AWS/ApplicationELB'], 
	'TargetTLSNegotiationErrorCount': ['AWS/ApplicationELB'], 
	'LambdaTargetProcessedBytes': ['AWS/ApplicationELB'], 
	'ELBAuthError': ['AWS/ApplicationELB'], 
	'ELBAuthFailure': ['AWS/ApplicationELB'], 
	'ELBAuthLatency': ['AWS/ApplicationELB'], 
	'ELBAuthRefreshTokenSuccess': ['AWS/ApplicationELB'], 
	'ELBAuthSuccess': ['AWS/ApplicationELB'], 
	'ELBAuthUserClaimsSizeExceeded': ['AWS/ApplicationELB'], 
}
